apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dztegn3w8-go 
  janus-idp.io/tekton: dztegn3w8-go
  backstage.io/kubernetes-id: dztegn3w8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dztegn3w8-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml